config/routes.rb
Rails.application.routes.draw do
  root 'rooms#show'
  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
  	@messages = Message.all

  end
  def create
  	@message = params[:room][:message]
    @name = params[:room][:name]
  	respond_to do |format|
  		format.html{redirect_to root_path}
  		format.js
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class = "message">
	<%= message.name %>: <%= message.message %>
</div>

app/views/rooms/create.js.erb
App.room.speak("<%= @name %>","<%= @message %>");

app/views/rooms/show.html.erb
<h1>Chat App</h1>
<div>
	<div id = "messages">
		<%= render @messages %>
	</div>
	<div id = "text-input">
		<%= form_for(:room, url: rooms_path, remote: true) do |f| %>
		<%= f.label :name %>
		<br>
		<%= f.text_field :name %>
		<br>
		<%= f.label :message %>
		<br>
		<%= f.text_area :message, class: "message-input" %>
		<%= f.submit "Send" %>
		<% end %>

	</div>
</div>